# -*- coding: utf-8 -*-
"""q1 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YNtkiCN2OvmRnIVdCg6VR5kk44SpH8wp
"""

a = int(input("enter the first number : "))
b = int(input("enter the second number : "))
print("the sum of the two given numbers is ", a+b)