# -*- coding: utf-8 -*-
"""q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wgf0QTWqUkEiXv6UDKRd6h0Q1iOZJrQV
"""

string = input("enter the string : ")
print(string[ : :2])