# -*- coding: utf-8 -*-
"""q3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CZ9_SFy9wI0zAOvby7I8GpNSgy88eBFy
"""

students_num =int(input('Enter the number of students whose marks should be entered : '))
table=[['Roll No','Name','Marks']]
for i in range(students_num):
    roll_no =input('Enter the roll number of the student whose marks you should enter : ')
    name=input('Enter the name of this student : ')
    marks=float(input('Enter the marks obtained by this students : '))
    table.append([roll_no,name,marks])
for i in range(len(table)):
    for m in range(len(table[i])):
        n=table[i][m]
        print(n,end='\t')
    print('\n')
o=int(input('Enter the number of the row which you want to print : '))
for i in table[o]:
    print(i,end='\t')