# -*- coding: utf-8 -*-
"""q4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uYITKUh7Gw6PKlePnXaJ7utNO2RXaHSO
"""

print("enter a number")
num = int(input())
sum = 0
rem = 0
ori = num
while num != 0:
    rem = num % 10
    sum = sum * 10 + rem
    num = int(num / 10)
if sum == ori:
    print("TRUE")
else:
    print("FALSE")