# -*- coding: utf-8 -*-
"""q5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CL2LAnHCo0PiGQYDQUZDwximb8mwd1yx
"""

for i in range(1,6):
    print(" "*(6-i)+"* "*i)