# -*- coding: utf-8 -*-
"""q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_iV-QSlii67dL5pEt1lSkEfcSFn81bBZ
"""

import numpy as np
a = int(input("Enter the first number : "))
b = int(input("Enter the second number : "))
c = np.array([i for i in range(a,(b+1),1)])
n = 5
d = np.zeros(len(c)+((len(c)-1)*n))
d[0:len(d):(n+1)]=c
print(d)