# -*- coding: utf-8 -*-
"""q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_iV-QSlii67dL5pEt1lSkEfcSFn81bBZ
"""

import numpy as np

a = [] 
b = [] 
 
a = [int(item) for item in input("Enter the First Array : ").split()]
b = [int(item) for item in input("Enter the Second Array : ").split()]

a = np.array(a)
b = np.array(b)

comp = a == b
equal = comp.all()
  
print(equal)