# -*- coding: utf-8 -*-
"""q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_iV-QSlii67dL5pEt1lSkEfcSFn81bBZ
"""

import numpy as np
print(0 * np.nan)
print(np.nan != np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)