# -*- coding: utf-8 -*-
"""q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_iV-QSlii67dL5pEt1lSkEfcSFn81bBZ
"""

import pandas as pd
ser = pd.Series(['amrita','school','of','engineering','chennai','campus'])
title = ser.str.title()
a = ' '
for i in title :
  a += i + " "
print(a)