# -*- coding: utf-8 -*-
"""q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_iV-QSlii67dL5pEt1lSkEfcSFn81bBZ
"""

import numpy as np
  
array1 = np.array([[1, 3, 3], [-4, 5, 0],[-2, 7, 21]])
array2 = np.array([[48, 5, -7], [6, 5, 9],[3, 6, 99]])
   
print ("1st array : \n", array1) 
print ("2nd array : \n", array2) 
    
added = np.add(array1, array2) 
print ("added array : \n", added)